# Service type: RPSA or REST
serviceType=RPSA

# RPSA configuration
rpsaServerUrl=https://us-dev-rp.identityx-cloud.com:443/env4-rp3/
#rpsaServerUrl=https://emea-rp.identityx-cloud.com/daonfuda-fido/

# REST configuration
restServerUrl=https://us-dev-env4.identityx-cloud.com:443/fido
restPath=IdentityXServices/rest/v1
restAppId=mobileteamfido
restRegPolicy=reg
restAuthPolicy=auth
restUsername=admin2
restPassword=admin2
